mongodb:
  hosts:
  - mongo1.prod.biola.edu
  - mongo2.prod.biola.edu
  - mongo3.prod.biola.edu

email:
  delivery_method: smtp
  options:
    address: 'cgp.biola.edu'

redis:
  url: "redis://redis1.prod.biola.edu:6379/0"