mongodb:
  hosts:
  - mongo1a.prod.biola.edu
  - mongo1b.prod.biola.edu

email:
  delivery_method: smtp
  options:
    address: postfix.biola.edu

redis:
  url: "redis://redis1.prod.biola.edu:6379/0"
